name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install clang-format-10
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-10

    - name: Format code
      run: |
        find . -iname *.h -o -iname *.cpp | xargs clang-format-10 -i

    - name: Build and test
      run: |
        mkdir build && cd build
        cmake ..
        make
        make test
